<div class="row-contact">
    <nav class="breadcrumb">
        <a class="first" href="Laurent-Guigues">Accueil</a><span class="chevron">&gt;</span><span class="current-page">Me contacter</span>
    </nav>
    <section>
        <h3>Me contacter</h3>
        <?php if(array_key_exists('errors', $_SESSION)) : ?>
            <div class="errors">
                <?= '<ul>'.implode('<li>',$_SESSION['errors']).'</ul>'; ?>
            </div>
        <?php endif; ?>
        <?php if(array_key_exists('success', $_SESSION)) : ?>
            <div class="success">
                <?= '<ul>'.implode('<li>',$_SESSION['success']).'</ul>'; ?>
        </div>
        <?php endif; ?>
        <div class="contact border">
            <form action="index.php?page=contact" method="post">
                <div class="home-form">
                    <div class="field">
                        <label for="lastName">Nom *</label>
                        <div class="value"><input type="text" id="lastName" name="lastName" value="<?= isset($_SESSION['formData']['lastName']) ? htmlspecialchars($_SESSION['formData']['lastName']) : '' ?>" placeholder="Nom" required>
                        </div>
                    </div>
                    <div class="field">
                        <label for="firstName">Prénom</label>
                        <div class="value"><input type="text" id="firstName" name="firstName" value="<?= isset($_SESSION['formData']['firstName']) ? htmlspecialchars($_SESSION['formData']['firstName']) : '' ?>" placeholder="Prénom">
                        </div>
                    </div>
                    <div class="field">
                        <label for="email">Email *</label>
                        <div class="value"><input type="email" id="email" name="email" value="<?= isset($_SESSION['formData']['email']) ? htmlspecialchars($_SESSION['formData']['email']) : '' ?>" placeholder="votre@email" required></div>
                    </div>
                    <div class="field">
                        <label for="phone">Téléphone</label>
                        <div class="value"><input type="tel" id="phone" name="phone" value="<?= isset($_SESSION['formData']['phone']) ? htmlspecialchars($_SESSION['formData']['phone']) : '' ?>" placeholder="01.02.03.04.05" pattern="[0-9]{2}.[0-9]{2}.[0-9]{2}.[0-9]{2}.[0-9]{2}"></div>
                    </div>
                    <div class="field">
                        <label for="object">Objet</label>
                        <div class="value"><input type="text" id="object" name="object" value="<?= isset($_SESSION['formData']['object']) ? htmlspecialchars($_SESSION['formData']['object']) : '' ?>" placeholder="Objet du message"></div>
                    </div>
                    <div class="field">
                        <label for="message">Message</label>
                        <div class="value">
                            <textarea id="message" name="message" placeholder="Votre message" rows="10" cols="24">
                            <?= isset($_SESSION['formData']['message']) ? htmlspecialchars($_SESSION['formData']['message']) : '' ?>
                            </textarea>
                        </div>
                    </div>
                    <span class="info-required">Les champs marqués * sont obligatoires</span>
                </div>
                <div class="rgpd">
                    <input class="checkbox" type="checkbox" name="rgpd">
                    <label>J'accepte la politique de confidentialité. <a id="openModal" href="#modal">(Cliquez pour lire)</a></label>
                </div>
                <div class="remarks">
                    <label for="remarks">Remarque</label>
                    <input type="text" name="remarks" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$" placeholder="nom@domaine.com">
                </div>
                <input class="button form-button" type="submit" name="submit" id="button" value="Envoyer">
            </form>
        </div>
    </section>
    <aside id="modal" class="legal-notice-off">
        <div class="legal-notice-container">
            <span id="closeModal" class="close-modal">Fermer</span>
            <h1>Mentions légales</h1>
            <div class="legal-notice">
                <p>Merci de lire avec attention les différentes modalités d'utilisation du présent site avant d'y parcourir ses pages. En vous connectant sur ce site, vous acceptez sans réserves les présentes modalités. Aussi, conformément à l'article n°6 de la Loi n°2004-575 du 21 Juin 2004 pour la confiance dans l'économie numérique, les responsables du présent site internet <a href="https://www.lguiguesdeveloppement.fr">lguiguesdeveloppement.fr</a></p>
                <h3>Editeur du site</h3>
                <p>Laurent GUIGUES</p>
                <p>Responsable publication: Laurent GUIGUES</p>
                <p>Email : contact@lguiguesdeveloppement.fr</p>
                <p>Site web : <a href="https://www.lguiguesdeveloppement.fr">www.lguiguesdeveloppement.fr</a></p>
                <h3>Hébergement</h3>
                <p>Hébergeur : PlanetHoster 4416 Louis B. Mayer - Laval (Grand Montréal), Québec H7P 0G1 - Canada</p>
                <p>Site web : www.planethoster.com/fr/</p>
                <h3>Développement</h3>
                <p>Laurent GUIGUES</p>
                <p>Site web : <a href="https://www.lguiguesdeveloppement.fr">www.lguiguesdeveloppement.fr</a></p>
                <h3>Conditions d'utilisation</h3>
                <p>Ce site <a href="https://www.lguiguesdeveloppement.fr">www.lguiguesdeveloppement.fr</a> est proposé en différents langages web (HTML5, Javascript, CSS, etc ...) pour un meilleur confort d'utilisation et un graphisme plus agréable, nous vous recommandons de recourir à des navigateurs modernes comme Edge, Safari, Firefox, Google Chrome, etc...
                    Laurent GUIGUES met en oeuvre tous les moyens dont il dispose, pour assurer une information fiable et une mise à jour fiable de son site internet. Toutefois, des erreurs ou omissions peuvent survenir. L'internaute devra donc s'assurer de l'exactitude des informations auprès de Laurent GUIGUES, et signaler toutes modifications du site qu'il jugerait utile. Laurent GUIGUES n'est en aucun cas responsable de l'utilisation faite de ces informations, et de tout préjudice direct ou indirect pouvant en découler.</p>
                <h3>Liens hypertextes</h3>
                <p>Les sites internet peuvent offrir des liens vers d'autres sites internet ou d'autres ressources disponibles sur Internet. Laurent GUIGUES ne dispose d'aucun moyen pour contrôler les sites en connexion avec ses sites internet, ne répond pas de la disponibilité de tels sites et sources externes, ni ne la garantit.
                    Les utilisateurs, les abonnés et les visiteurs des sites internet ne peuvent pas mettre en place un hyperlien en direction de ce site sans l'autorisation expresse et préalable de Laurent GUIGUES.
                    Dans l'hypothèse où un utilisateur ou visiteur souhaiterait mettre en place un hyperlien en direction de ce site internet, il lui appartiendra d'adresser un email accessible sur le site afin de formuler sa demande de mise en place d'un hyperlien. Laurent GUIGUES se réserve le droit d'accepter ou de refuser un hyperlien sans avoir à en justifier sa décision.</p>
                <h3>Services fournis</h3>
                <p>Laurent GUIGUES s'efforce de fournir sur le site <a href="https://www.lguiguesdeveloppement.fr">www.lguiguesdeveloppement.fr</a> des informations aussi précises que possible. les renseignements figurant sur le site ne sont pas exhaustifs et les photos non contractuelles. Ils sont donnés sous réserve de modifications ayant été apportées depuis leur mise en ligne. Par ailleurs, tous les informations indiquées sur le site sont données à titre indicatif, et sont susceptibles de changer ou d'évoluer sans préavis.</p>
                <h3>Propriété intellectuelle</h3>
                <p>Tout le contenu du présent site incluant, de façon non limitative, les graphismes, images, textes, vidéos, animations, sons, logos, gifs et icônes ainsi que leur mise en forme sont la propriété exclusive de Laurent GUIGUES à l'exception des marques, logos ou contenus appartenant à d'autres sociétés partenaires ou auteurs.
                    Toute reproduction, distribution, modification, adaptation, retransmission ou publication, même partielle, de ces différents éléments est strictement interdite sans l'accord exprès par écrit de Laurent GUIGUES. Cette représentation ou reproduction, par quelque procédé que ce soit, constitue une contrefaçon sanctionnée par les articles L.335-2 et suivants du Code de la propriété intellectuelle. Le non-respect de cette interdiction constitue une contrefaçon pouvant engager la responsabilité civile et pénale du contrefacteur. En outre, les propriétaires des contenus copiés pourraient intenter une action en justice à votre encontre.</p>
                <h3>Litiges</h3>
                <p>Les présentes conditions du site sont régies par les lois françaises et toute contestation ou litiges qui pourraient naître de l'interprétation ou de l'exécution de celles-ci seront de la compétence exclusive des tribunaux. La langue de référence, pour le règlement de contentieux éventuels, est le français.</p>
                <h3>RGPD / Données Personnelles</h3>
                <p>De manière générale, vous n'êtes pas tenu de nous communiquer vos données personnelles lorsque vous visitez le site Internet <a href="https://www.lguiguesdeveloppement.fr">www.lguiguesdeveloppement.fr</a>.
                    Cependant, ce principe comporte certaines exceptions. En effet, vous pouvez être amenés à nous communiquer certaines données telles que : votre nom, prénom, adresse électronique ou votre numéro de téléphone.
                    Dans tous les cas, vous pouvez refuser de fournir vos données personnelles. Dans ce cas, vous ne pourrez pas utiliser les services du site, notamment celui de solliciter des renseignements. Vos données sont confidentielles et privées et ne sont pas transmisent à des tiers.
                    Les bases de données sont protégées par les dispositions de la loi du 1er juillet 1998 transposant la directive 96/9 du 11 mars 1996 relative à la protection juridique des bases de données.</p>
                <span class="date-legal-notice">Mentions légales au 13 février 2022</span>
            </div>
        </div>
    </aside>
</div>
<script src="www/assets/js/modal.js"></script>
<?php
unset($_SESSION['formData']);
unset($_SESSION['errors']);
unset($_SESSION['success']);
?>