<section>
    <div class="intro">
        <div class="animate-text">
            <h1 class="name">GUIGUES Laurent</h1>
            <h2 class="job">Développeur Web Junior</h2>
        </div>
    </div>
</section>

<section>
    <h3>Présentation</h3>
    <div class="clearfix  presentation">
        <p>Passionné par l’informatique depuis l’âge de 8 ans, j’ai toujours eu à cœur un jour ou l’autre de
            faire un métier qui puisse allier ma passion et apporter mes compétences à une entreprise.</p>
        <div class="portrait">
            <a href="a-propos">
                <img class="portrait-img" src="www/assets/img/portrait_guigues_laurent.webp" alt="Portrait GUIGUES Laurent">
            </a>
        </div>
        <p>Après plusieurs années dans le commerce en grandes distribution spécialisés, j’ai franchi un cap
            important dans ma carrière professionnel en relevant un nouveau défi.</p>
        <p>En septembre 2021, j’ai commencé une reconversion pour devenir développeur intégrateur web. Avec la
            3W Académy et son Bootcamp intensif de 3 mois en distanciel, j’ai pu apprendre les 5 langages les
            plus utilisés dans le développement web. (Html, Css, Javascript, Php, Sql). Les différents
            exercices et le projet de fin de formation m’ont permis de mettre en pratique toutes ces
            connaissances.</p>
        <p>En 2022, je souhaite trouver une entreprise dans laquelle je pourrais continuer d’apprendre tout en
            apportant mes expériences passées. Autodidacte par nature, je suis rigoureux, organisé,
            communiquant, persévérant, curieux et surtout l'envie de relever de nouveaux challenges.</p>
    </div>
</section>

<section>
    <h3>Dernier évènement</h3>
    <div class="clearfix events">
        <p>J'ai obtenu la note de 300/1000 à cette certification TOSA PHP - Test du 5 mai 2022</p>
        <div class="tosa-certification">
            <a href="https://www.tosa.org/FR/Index?param=WmhnUlBvN0g5SXBvUnZTaVVmbkgrQmo3Y2VSc0pkSy9KSndaR0JwMVVDNmp4ZHYrcUtBZUNOMWEwbmRpMS80M0J6SC9UYXhWZlEyeVNXOTVrSEhCeXc9PTo6otg-30vUtL8Zq9RjuhTvng" target="_blank">
                <img class="img-tosa-certification" src="www/assets/img/certifications/tosa_php_laurent_guigues_min.png" alt="Illustration Certification Tosa PHP">
            </a>
        </div>
        <ul class="events-links">
            <li>
                <a href="https://www.tosa.org/FR/Index?param=WmhnUlBvN0g5SXBvUnZTaVVmbkgrQmo3Y2VSc0pkSy9KSndaR0JwMVVDNmp4ZHYrcUtBZUNOMWEwbmRpMS80M0J6SC9UYXhWZlEyeVNXOTVrSEhCeXc9PTo6otg-30vUtL8Zq9RjuhTvng" target="_blank">Lien vers la certification</a>
            </li>
            <li>
                <a href="www/pdf/Tosa_PHP_laurent_guigues.pdf" target="_blank">Télécharger la certification format pdf</a>
            </li>
        </ul>
    </div>
</section>

<section>
    <div class="formations">
        <h3 class="title-formation">Ma formation avec la <a href="https://www.3wa.fr" title="Ecole de formation 3W Academy">
                <img src="www/assets/img/logos/min_logo_3w_academy_min.webp" alt="Logo de la 3W Academy"></a>
        </h3>
        <h3>Quelques exemples...</h3>
        <div class="flex-blocks">
            <div class="block html-css reveal-1">
                <a href="https://www.laurentguigues.fr/projects/archi_design/index.html" target="_blank" title="ArchiDesign, votre intérieur à la carte">
                    <picture>
                        <source media="(max-width: 320px)" srcset="www/assets/img/visuals/archidesign_295_min.webp">
                        <source media="(max-width: 767px)" srcset="www/assets/img/visuals/archidesign_385_min.webp">
                        <source media="(max-width: 1399px)" srcset="www/assets/img/visuals/archidesign_650_min.webp">
                        <source media="(max-width: 1920px)" srcset="www/assets/img/visuals/archidesign_743_min.webp">
                        <img src="www/assets/img/visuals/archidesign_743_min.webp" alt="ArchiDesign, votre intérieur à la carte">
                    </picture>
                    <div class="thumbnail">
                        <img src="www/assets/img/svg/logo_html.svg" alt="Logo Html">
                        <img src="www/assets/img/svg/logo_css.svg" alt="Logo Css">
                    </div>
                </a>
            </div>
            <div class="block javascript reveal-2">
                <a href="https://www.laurentguigues.fr/projects/address_book/index.html" target="_blank" title="Mon carnet d'adresse">
                    <picture>
                        <source media="(max-width: 320px)" srcset="www/assets/img/visuals/carnet_adresse_295_min.webp">
                        <source media="(max-width: 767px)" srcset="www/assets/img/visuals/carnet_adresse_385_min.webp">
                        <source media="(max-width: 1399px)" srcset="www/assets/img/visuals/carnet_adresse_650_min.webp">
                        <source media="(max-width: 1920px)" srcset="www/assets/img/visuals/carnet_adresse_743_min.webp">
                        <img src="www/assets/img/visuals/carnet_adresse_743_min.webp" alt="Mon carnet d'adresse">
                    </picture>
                    <div class="thumbnail">
                        <img src="www/assets/img/svg/logo_javascript.svg" alt="Logo Javascript">
                    </div>
                </a>
            </div>
            <div class="block php-sql reveal-3">
                <a href="https://www.laurentguigues.fr/projects/restaurant_bistrot/index.php" target="_blank" title="Restaurant - Le Bistro">
                    <picture>
                        <source media="(max-width: 320px)" srcset="www/assets/img/visuals/restaurant_bistrot_295_min.webp">
                        <source media="(max-width: 767px)" srcset="www/assets/img/visuals/restaurant_bistrot_385_min.webp">
                        <source media="(max-width: 1399px)" srcset="www/assets/img/visuals/restaurant_bistrot_650_min.webp">
                        <source media="(max-width: 1920px)" srcset="www/assets/img/visuals/restaurant_bistrot_743_min.webp">
                        <img src="www/assets/img/visuals/restaurant_bistrot_743_min.webp" alt="Restaurant - Le Bistro">
                    </picture>
                    <div class="thumbnail">
                        <img src="www/assets/img/svg/logo_php.svg" alt="Logo Php">
                        <img src="www/assets/img/svg/logo_mysql.svg" alt="Logo MySql">
                    </div>
                </a>
            </div>
            <div class="block final-project reveal-4">
                <a href="https://boutondor.lguiguesdeveloppement.fr" target="_blank" title="Bouton d'Or - Projet de fin de formation">
                    <picture>
                        <source media="(max-width: 320px)" srcset="www/assets/img/visuals/bouton_dor_295_min.webp">
                        <source media="(max-width: 767px)" srcset="www/assets/img/visuals/bouton_dor_385_min.webp">
                        <source media="(max-width: 1399px)" srcset="www/assets/img/visuals/bouton_dor_650_min.webp">
                        <source media="(max-width: 1920px)" srcset="www/assets/img/visuals/bouton_dor_743_min.webp">
                        <img src="www/assets/img/visuals/bouton_dor_743_min.webp" alt="Bouton d'Or - Fleuriste à Bléré - Indre et Loire (37)">
                    </picture>
                    <div class="thumbnail">
                        <img src="www/assets/img/svg/logo_html.svg" alt="Logo Html">
                        <img src="www/assets/img/svg/logo_css.svg" alt="Logo Css">
                        <img src="www/assets/img/svg/logo_javascript.svg" alt="Logo Javascript">
                        <img src="www/assets/img/svg/logo_php.svg" alt="Logo Php">
                        <img src="www/assets/img/svg/logo_mysql.svg" alt="Logo MySql">
                    </div>
                </a>
            </div>
        </div>
    </div>
</section>
<address>
    <p class="title-address">Mon adresse
    <p>
        <a id="displayMap" class="font-icon address" href="#addressIframe">35 Chemin du verney - 73220
            Argentine</a>
    <div class="box-map">
        <iframe sandbox="allow-scripts" class="iframe-map" id="addressIframe" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d699.3738509112278!2d6.299106311498398!3d45.47996777705833!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x478bcc73f68f8ecb%3A0xba754a906949935!2s35%20Chem.%20du%20Verney%2C%2073220%20Argentine!5e0!3m2!1sfr!2sfr!4v1638101938792!5m2!1sfr!2sfr" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
    </div>
    <p class="font-icon phone">06 62 54 22 70</p>
    <a href="me-contacter">Me contacter</a>
</address>
<script src="www/assets/js/home.js"></script>