<div class="row-formation">
    <nav class="breadcrumb">
        <a class="first" href="Laurent-Guigues">Accueil</a><span class="chevron">&gt;</span><span class="current-page">Ma formation</span>
    </nav>
    <section>
        <div class="formation">
            <h1>Ma formation</h1>
            <p>Vous pourrez voir le travail effectué tout au long de cette formation intensive de 3 mois(BootCamp) au travers de ces quelques réalisations.</p>
        </div>
    </section>
    <article>
        <h2>Le Html et le CSS</h2>
        <p>Dans cette première partie, vous allez découvrir mon travail en Html 5 et Css 3. Ces exercices m'ont appris l'architecture html, puis le css et la mise en pratique de la conception en mobile first.</p>
        <h3>Exercice New York</h3>
        <p>Ce premier exercice consiste à créer une page sur la ville de New York. En partant d'une maquette (en Jpeg), il faut créer la structure html et le css pour que l'ensemble corresponde à la maquette de départ. On dispose d'instructions de bases, comme la taille des textes, les couleurs, les polices de caractère ou la largeur du contenu. Après il faut se lancer !</p>
        <div class="visual">
            <a href="projects/new_york" target="_blank" title="Exercice New York">
                <picture>
                    <source media="(max-width: 320px)" srcset="www/assets/img/visuals/newyork_295_min.jpg">
                    <source media="(max-width: 767px)" srcset="www/assets/img/visuals/newyork_385_min.jpg">
                    <source media="(max-width: 1399px)" srcset="www/assets/img/visuals/newyork_650_min.jpg">
                    <source media="(max-width: 1920px)" srcset="www/assets/img/visuals/newyork_743_min.jpg">
                    <img src="www/assets/img/visuals/newyork_743_min.jpg" alt="Une belle page sur la ville de New York">
                </picture>
            </a>
        </div>
        <h3>Exercice Hello World</h3>
        <p>Ce deuxième exercice est une page de carnet de voyage avec un lien vers une seconde page. Quelques difficultées supplémentaires pour maitriser les notions vues dans les cours précédents.</p>
        <div class="visual">
            <a href="projects/hello_world" target="_blank" title="Exercice Hello World">
                <picture>
                    <source media="(max-width: 320px)" srcset="www/assets/img/visuals/helloworld_295_min.jpg">
                    <source media="(max-width: 767px)" srcset="www/assets/img/visuals/helloworld_385_min.jpg">
                    <source media="(max-width: 1399px)" srcset="www/assets/img/visuals/helloworld_650_min.jpg">
                    <source media="(max-width: 1920px)" srcset="www/assets/img/visuals/helloworld_743_min.jpg">
                    <img src="www/assets/img/visuals/helloworld_743_min.jpg" alt="Un carnet de voyage">
                </picture>
            </a>
        </div>
        <h3>Exercice Move Academy</h3>
        <p>Un troisième exercice en une page, avec un tableau et un formulaire. Des instructions épurés pour apprendre à travailler juste avec un visuel.</p>
        <div class="visual">
            <a href="projects/move_academy" target="_blank" title="Exercice Move Academy">
                <picture>
                    <source media="(max-width: 320px)" srcset="www/assets/img/visuals/moveacademy_295_min.jpg">
                    <source media="(max-width: 767px)" srcset="www/assets/img/visuals/moveacademy_385_min.jpg">
                    <source media="(max-width: 1399px)" srcset="www/assets/img/visuals/moveacademy_650_min.jpg">
                    <source media="(max-width: 1920px)" srcset="www/assets/img/visuals/moveacademy_743_min.jpg">
                    <img src="www/assets/img/visuals/moveacademy_743_min.jpg" alt="Home page d'une compagnie de dance.">
                </picture>
            </a>
        </div>
        <h3>Exercice ArchiDesign</h3>
        <p>Ce quatrième exercice avec plusieurs pages devait être réaliser en retrofitting (de la version Desktop vers la version mobile). Une petite difficulté et un raisonnement à l'envers dans l'utilisation des média queries. Au final un exercice très intérressant que je vous laisse découvrir.</p>
        <div class="visual">
            <a href="projects/archi_design" target="_blank" title="Exercice ArchiDesign">
                <picture>
                    <source media="(max-width: 320px)" srcset="www/assets/img/visuals/archidesign_295_min.jpg">
                    <source media="(max-width: 767px)" srcset="www/assets/img/visuals/archidesign_385_min.jpg">
                    <source media="(max-width: 1399px)" srcset="www/assets/img/visuals/archidesign_650_min.jpg">
                    <source media="(max-width: 1920px)" srcset="www/assets/img/visuals/archidesign_743_min.jpg">
                    <img src="www/assets/img/visuals/archidesign_743_min.jpg" alt="Un site pour un architecte.">
                </picture>
            </a>
        </div>
    </article>
    <article>
        <h2>Le javascript</h2>
        <p>Cette seconde partie vous montre mon travail en javascript. Des petits exercices pour assimiler les notions de base du JS.</p>
        <h3>Un carnet d'adresse personnel</h3>
        <p>Ce carnet d'adresse utilise le localStorage pour conserver les adresses que l'on saisie. On peut à tout moment modifer une adresse ou la supprimer. Ce fut l'occasion pendant cet exercice de découvrir aussi VueJs.</p>
        <div class="visual">
            <a href="projects/address_book" target="_blank" title="Un carnet d'adresse avec VueJs">
                <picture>
                    <source media="(max-width: 320px)" srcset="www/assets/img/visuals/carnet_adresse_295_min.jpg">
                    <source media="(max-width: 767px)" srcset="www/assets/img/visuals/carnet_adresse_385_min.jpg">
                    <source media="(max-width: 1399px)" srcset="www/assets/img/visuals/carnet_adresse_650_min.jpg">
                    <source media="(max-width: 1920px)" srcset="www/assets/img/visuals/carnet_adresse_743_min.jpg">
                    <img src="www/assets/img/visuals/carnet_adresse_743_min.jpg" alt="Un carnet d'adresse avec VueJs">
                </picture>
            </a>
        </div>
        <h3>Objectif Lune</h3>
        <p>Un petit jeu pour faire décoller une fusée et se rendre sur la lune. Etes-vous êtes prêt pour ce long voyage ?</p>
        <div class="visual">
            <a href="projects/rocket_moon" target="_blank" title="Objectif Lune">
                <picture>
                    <source media="(max-width: 320px)" srcset="www/assets/img/visuals/rocketmoon_295_min.jpg">
                    <source media="(max-width: 767px)" srcset="www/assets/img/visuals/rocketmoon_385_min.jpg">
                    <source media="(max-width: 1399px)" srcset="www/assets/img/visuals/rocketmoon_650_min.jpg">
                    <source media="(max-width: 1920px)" srcset="www/assets/img/visuals/rocketmoon_743_min.jpg">
                    <img src="www/assets/img/visuals/rocketmoon_743_min.jpg" alt="Un long voyage vers la lune">
                </picture>
            </a>
        </div>
        <h3>Validation Formulaire</h3>
        <p>Les formulaires sont la principale intéraction entre les utilisateurs et la machine pour demander une information, créer un compte... Le contrôle de la validation des champs avec JS permet d'accompagner l'utilisateur en cas d'erreur avec des messages personnalisés et intuitifs. Cet exercice montre ce travail.</p>
        <div class="visual">
            <a href="projects/form_validator" target="_blank" title="Validation de forumaire avec Js">
                <picture>
                    <source media="(max-width: 320px)" srcset="www/assets/img/visuals/formvalidator_295_min.jpg">
                    <source media="(max-width: 767px)" srcset="www/assets/img/visuals/formvalidator_385_min.jpg">
                    <source media="(max-width: 1399px)" srcset="www/assets/img/visuals/formvalidator_650_min.jpg">
                    <source media="(max-width: 1920px)" srcset="www/assets/img/visuals/formvalidator_743_min.jpg">
                    <img src="www/assets/img/visuals/formvalidator_743_min.jpg" alt="La validation d'un formulaire avec Javascript">
                </picture>
            </a>
        </div>
        <h3>Requête AJAX</h3>
        <p>Un petit exercice pour découvrir les requêtes AJAX avec la bibliothèque JQUERY.</p>
        <div class="visual">
            <a href="projects/ajax_requests" target="_blank" title="Requêtes Ajax avec Jquery">
                <picture>
                    <source media="(max-width: 320px)" srcset="www/assets/img/visuals/ajaxrequest_295_min.jpg">
                    <source media="(max-width: 767px)" srcset="www/assets/img/visuals/ajaxrequest_385_min.jpg">
                    <source media="(max-width: 1399px)" srcset="www/assets/img/visuals/ajaxrequest_650_min.jpg">
                    <source media="(max-width: 1920px)" srcset="www/assets/img/visuals/ajaxrequest_743_min.jpg">
                    <img src="www/assets/img/visuals/ajaxrequest_743_min.jpg" alt="Requête AJAX avec utilisation de JQUERY">
                </picture>
            </a>
        </div>
    </article>
    <article>
        <h2>Le Php et MySql</h2>
        <p>Dans cette dernière partie, c'est le travail de l'ombre. La partie que l'utilisateur ne voit pas, un travail de programmation pour assembler le puzzle. Architecture MVC, Programmation Orientée Objet, connexion à la base de donné, requêtes Sql préparées... Voici quelques exemples de mon travail.</p>
        <h3>Un blog</h3>
        <p>Pour commencer l'apprentissage, quoi de mieux que la réalisation d'un blog.</p>
        <div class="visual">
            <a href="projects/blog" target="_blank" title="Passion Blog">
                <picture>
                    <source media="(max-width: 320px)" srcset="www/assets/img/visuals/blog_295_min.jpg">
                    <source media="(max-width: 767px)" srcset="www/assets/img/visuals/blog_385_min.jpg">
                    <source media="(max-width: 1399px)" srcset="www/assets/img/visuals/blog_650_min.jpg">
                    <source media="(max-width: 1920px)" srcset="www/assets/img/visuals/blog_743_min.jpg">
                    <img src="www/assets/img/visuals/blog_743_min.jpg" alt="Un blog">
                </picture>
            </a>
        </div>
        <h3>Le restaurant</h3>
        <p>Après un blog, sans POO et sans MVC, voici le site du restaurant, le Bistrot. Architecture en MVC et Poo.</p>
        <div class="visual">
            <a href="projects/restaurant_bistrot" target="_blank" title="Restaurant Le Bistrot">
                <picture>
                    <source media="(max-width: 320px)" srcset="www/assets/img/visuals/restaurant_bistrot_295_min.jpg">
                    <source media="(max-width: 767px)" srcset="www/assets/img/visuals/restaurant_bistrot_385_min.jpg">
                    <source media="(max-width: 1399px)" srcset="www/assets/img/visuals/restaurant_bistrot_650_min.jpg">
                    <source media="(max-width: 1920px)" srcset="www/assets/img/visuals/restaurant_bistrot_743_min.jpg">
                    <img src="www/assets/img/visuals/restaurant_bistrot_743_min.jpg" alt="Restaurant le Bistrot, spécialités Savoyarde">
                </picture>
            </a>
        </div>
    </article>
</div>