<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="shortcut icon" href="www/assets/img/favicon/favicon.ico" type="image/x-icon">
    <meta name="robots" content="index,follow">
    <meta name="title" content="Laurent GUIGUES | Développeur Web Fullstack Junior">
    <meta name="description" content="<?= $metaDescription ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="www/assets/css/normalize.css">
    <link rel="stylesheet" type="text/css" href="www/assets/css/style.css">
    <title><?= $titlePage ?></title>

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://www.laurentguigues.fr">
    <meta property="og:title" content="Laurent GUIGUES | Développeur Web Fullstack Junior">
    <meta property="og:description" content="Découvrez mes compétences de développeur intégrateur web dans ce portfolio. Formé avec la 3W Académy pour apprendre les 5 principaux langages du web : Html, Css, Js, Php et Sql. Faite le tour et n'hésitez pas à me contacter.">
    <meta property="og:image" content="https://www.laurentguigues.fr/www/assets/img/og/og_card.jpg">
    <meta property="og:image:alt" content="Portfolio de Laurent GUIGUES | Développeur Web Fullstack Junior">

    <!-- Twitter / Linkedin -->
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:url" content="https://www.laurentguigues.fr">
    <meta property="twitter:title" content="Laurent GUIGUES | Développeur Web Fullstack Junior">
    <meta property="twitter:description" content="Découvrez mes compétences de développeur intégrateur web dans ce portfolio. Formé avec la 3W Académy pour apprendre les 5 principaux langages du web : Html, Css, Js, Php et Sql. Faite le tour et n'hésitez pas à me contacter.">
    <meta property="twitter:image" content="https://www.laurentguigues.fr/www/assets/img/og/og_card.jpg">

    <meta name="author" content="Laurent GUIGUES">
</head>

<body class="scroll">
    <div class="container">
        <header>            
            <div class="nav-containt">
                <nav class="nav-laptop-desktop">
                    <a href="Laurent-Guigues">Accueil</a>
                    <a href="a-propos">A propos</a>
                    <a href="ma-formation">Ma formation</a>
                    <a href="mes-realisations">Mes réalisations</a>
                    <a href="me-contacter">Me contacter</a>
                </nav>
                <span id="menuClosed" class="icon-burger-menu-closed"></span>
                <div class="burger-menu">
                    <span id="closeMenu" class="close-menu">Menu</span>
                    <ul>
                        <li><a href="Laurent-Guigues">Accueil</a></li>
                        <li><a href="a-propos">A propos</a></li>
                        <li><a href="ma-formation">Ma formation</a></li>
                        <li><a href="mes-realisations">Mes réalisations</a></li>
                        <li><a href="me-contacter">Me contacter</a></li>
                    </ul>
                </div>
                <div class="links">
                    <a href="https://github.com/LGUIGUES">
                        <img class="icon" src="www/assets/img/svg/github-brands.svg" alt="Mon profil GitHub">
                    </a>
                    <a href="https://www.linkedin.com/in/laurent-guigues-25939b69/">
                        <img class="icon" src="www/assets/img/svg/linkedin-brands.svg" alt="Mon profil Linkedin">
                    </a>
                </div>
            </div>
        </header>
        <main class="content">
            <!-- Start Dynamic Part -->
            <?php require $template . ".phtml" ?>
            <!-- End Dynamic Part -->
        </main>
        <footer>
            <ul class="footer-nav">
                <li><a href="mentions-legales">Mentions légales</a></li>
            </ul>
            <p class="copyright">© GUIGUES Laurent 2021-<?= date('Y') ?></p>
            <p class="version">Portfolio version 1.0</p>
        </footer>
        <div>
            <span id="btnScrollTop" class="arrow-up hidden-btn-scroll"></span>
        </div>
    </div>
    <script src="www/assets/js/menu.js"></script>    
    <script src="www/assets/js/animation.js"></script>
    <script src="www/assets/js/app.js"></script>
    <noscript>Votre navigateur ne prends pas en charge le Javascript.</noscript>
</body>

</html>