<div class="row-production">
    <nav class="breadcrumb">
        <a class="first" href="Laurent-Guigues">Accueil</a><span class="chevron">&gt;</span><span class="current-page">Mes réalisations</span>
    </nav>
    <section>
        <h2>Mes Réalisations</h2>
        <p>Découvrez sur cette page mes réalisations. Certaines ne sont que des projets et d'autres sont en lignes.</p>
    </section>
    <article>
        <h2>Mon portfolio</h2>
        <p>Le portfolio sur lequel vous êtes en ce moment.</p>
        <div class="visual">
            <a href="https://www.laurentguigues.fr" title="Mon portfolio">
                <picture>
                    <source media="(max-width: 320px)" srcset="www/assets/img/visuals/portfolio_295_min.jpg">
                    <source media="(max-width: 767px)" srcset="www/assets/img/visuals/portfolio_385_min.jpg">
                    <source media="(max-width: 1399px)" srcset="www/assets/img/visuals/portfolio_650_min.jpg">
                    <source media="(max-width: 1920px)" srcset="www/assets/img/visuals/portfolio_743_min.jpg">
                    <img src="www/assets/img/visuals/portfolio_743_min.jpg" alt="Visuel portfolio">
                </picture>
            </a>
        </div>
    </article>
    <article>
        <h2>Projet fin de formation</h2>
        <p>Afin de valider cette formation pour l'obtention du diplôme de Développeur Intégrateur Web en application mobile, voici mon projet final. Il s'agit de la refonte du site internet d'un membre de ma famille qui possède un magasin de fleurs. Ce projet respecte les standards d'une architecture MVC et utilise la Poo. Un front-end et un back-end en mobile first avec 4 points de ruptures et utilisation de Flexbox.</p>
        <div class="visual">
            <a href="projects/boutondor" target="_blank" title="Bouton d'Or - Fleuriste à Bléré - Indre et Loire (37)">
                <picture>
                    <source media="(max-width: 320px)" srcset="www/assets/img/visuals/bouton_dor_295_min.jpg">
                    <source media="(max-width: 767px)" srcset="www/assets/img/visuals/bouton_dor_385_min.jpg">
                    <source media="(max-width: 1399px)" srcset="www/assets/img/visuals/bouton_dor_650_min.jpg">
                    <source media="(max-width: 1920px)" srcset="www/assets/img/visuals/bouton_dor_743_min.jpg">
                    <img src="www/assets/img/visuals/bouton_dor_743_min.jpg" alt="Visuel projet Bouton d'Or">
                </picture>
            </a>
        </div>
    </article>
    <section>
        <h2>Projet personnel en POO</h2>
    </section>
    <article>
        <h3>Une calculatrice IMC</h3>        
        <p>Travail sur la POO en PHP et utilisation de Bootstrap 5</p>
        <div class="visual">
        <a href="projects/calculatorImc" target="_blank" title="Calculatrice IMC">
                <picture>
                    <source media="(max-width: 320px)" srcset="www/assets/img/visuals/calculatrice_imc_295_min.jpg">
                    <source media="(max-width: 767px)" srcset="www/assets/img/visuals/calculatrice_imc_385_min.jpg">
                    <source media="(max-width: 1399px)" srcset="www/assets/img/visuals/calculatrice_imc_650_min.jpg">
                    <source media="(max-width: 1920px)" srcset="www/assets/img/visuals/calculatrice_imc_743_min.jpg">
                    <img src="www/assets/img/visuals/calculatrice_imc_743_min.jpg" alt="Visuel projet Calculatrice IMC">
                </picture>
            </a>
        </div>
    </article>
    <article>
        <h3>Un petit robot à personnaliser</h3>
        <p>Base Bootstrap 5, PHP avec template Twig et CSS personnel pour le Mobile Fisrt.</p>
        <div class="visual">
        <a href="projects/customRobot" target="_blank" title="Custom your Robot">
                <picture>
                    <source media="(max-width: 320px)" srcset="www/assets/img/visuals/custom_robot_295_min.jpg">
                    <source media="(max-width: 767px)" srcset="www/assets/img/visuals/custom_robot_385_min.jpg">
                    <source media="(max-width: 1399px)" srcset="www/assets/img/visuals/custom_robot_650_min.jpg">
                    <source media="(max-width: 1920px)" srcset="www/assets/img/visuals/custom_robot_743_min.jpg">
                    <img src="www/assets/img/visuals/custom_robot_743_min.jpg" alt="Visuel projet Custom Robot">
                </picture>
            </a>
        </div>
    </article>
</div>