<nav class="breadcrumb">
    <a class="first" href="Laurent-Guigues">Accueil</a><span class="chevron">&gt;</span><span class="current-page">A propos</span>
</nav> 
<article>
    <h2>Présentation</h2>
    <div class="clearfix  presentation">
        <p>Passionné par l’informatique depuis l’âge de 8 ans, j’ai toujours eu à cœur un jour ou l’autre de faire un métier qui puisse allier ma passion et apporter mes compétences à une entreprise.</p>
        <div class="portrait">
            <a href="a-propos">
                <img class="portrait-img" src="www/assets/img/portrait_guigues_laurent.webp" alt="Portrait GUIGUES Laurent">
            </a>
        </div>
        <p>Après plusieurs années dans le commerce en grandes distribution spécialisés, j’ai franchi un cap important dans ma carrière professionnel en relevant un nouveau défi.</p>
        <p>En septembre 2021, j’ai commencé une reconversion pour devenir développeur intégrateur web. Avec la 3W Académy et son Bootcamp intensif de 3 mois en distanciel, j’ai pu apprendre les 5 langages les plus utilisés dans le développement web. (Html, Css, Javascript, Php, Sql). Les différents exercices et le projet de fin de formation m’ont permis de mettre en pratique toutes ces connaissances.</p>
        <p>En 2022, je souhaite trouver une entreprise dans laquelle je pourrais continuer d’apprendre tout en apportant mes expériences passées. Autodidacte par nature, je suis rigoureux, organisé, communiquant, persévérant, curieux et surtout l'envie de relever de nouveaux challenges.</p>
    </div>
</article>
<article>
    <h3>Mon parcours Professionnel</h3>    
    <ul class="row-career">        
        <li>
            <div class="career-panel panel-left">
                <p class="title-panel">
                    2021-2022 Formation Développeur Web
                </p>
                <img src="www/assets/img/logos/logo_3wa_130_min.jpg" alt="Logo 3W Academy">
                <p>Formation intensive BootCamp 3 mois - Langages Html, Css, Javascript, Php et Sql</p>
            </div>
        </li>
        <li>
            <div class="career-panel panel-right">
                <p class="title-panel">
                    2014-2021 Chef de dépôt
                </p>
                <img src="www/assets/img/logos/logo_but_min.jpg" alt="Logo enseigne But">
                <p>Magasinier puis chef de dépôt dans un magasin du groupe</p>
            </div>
        </li>
        <li>
            <div class="career-panel panel-left">
                <p class="title-panel">
                    2013-2014 Technicien de maintenance
                </p>
                <img src="www/assets/img/logos/logo_ibis_min.jpg" alt="Logo hotel Ibis">
                <p>Rénovation des chambres et des salles de bains d'un hôtel indépendant sous la franchise Ibis</p>
            </div>
        </li>
        <li>
            <div class="career-panel panel-right">
                <p class="title-panel">
                    2011-2013 Adjoint de direction 
                </p>
                <img src="www/assets/img/logos/logo_weldom_min.jpg" alt="Logo enseigne Weldom">
                <p>Magasin de bricolage Weldom - Equipe de 5 personnes</p>
            </div>            
        </li>
        <li>
            <div class="career-panel panel-left">
                <p class="title-panel">
                    2008-2010 Gérant de Magasin
                </p>
                <img src="www/assets/img/logos/logo_weldom_min.jpg" alt="Logo enseigne Weldom">
                <p>Magasin de bricolage sous franchise Weldom - Equipe de 7 personnes</p>
            </div>
        </li>
        <li>
            <div class="career-panel panel-right">
                <p class="title-panel">
                    2003-2008 Directeur de magasin
                </p>
                <img src="www/assets/img/logos/logo_weldom_min.jpg" alt="Logo enseigne Weldom">
                <p>Magasin de bricolage sous franchise Weldom - Equipe de 7 personnes</p>
            </div>
        </li>
        <li>
            <div class="career-panel panel-left">
                <p class="title-panel">
                    1998-2003 Vendeur
                </p>
                <img src="www/assets/img/logos/vendeur_bricolage_min.jpg" alt="Magasin de bricolage">
                <p>Magasin de bricolage indépendant</p>
            </div>
        </li>
    </ul>
</article>
<div>
    <a class="download" href="www/pdf/cv_laurent_guigues_2022.pdf" target="_blank">Télécharger le CV au format pdf</a>
</div>